# Generated by Django 4.2.7 on 2024-01-02 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.IntegerField(choices=[(2, "2 o'clock"), (3, "3 o'clock"), (4, "4 o'clock"), (5, "5 o'clock"), (6, "6 o'clock"), (7, "7 o'clock"), (8, "8 o'clock"), (9, "9 o'clock"), (10, "10 o'clock"), (11, "11 o'clock"), (12, "12 o'clock")]),
        ),
        migrations.AlterField(
            model_name='book',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_property', to='accounts.day'),
        ),
    ]
