# Generated by Django 4.2.7 on 2024-01-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_book_date_alter_book_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_date_available',
            field=models.BooleanField(default=True),
        ),
    ]
