# Generated by Django 4.2.7 on 2024-01-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_book_is_date_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_date_available',
            field=models.BooleanField(default=True),
        ),
    ]
