# Generated by Django 4.2.7 on 2024-01-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_book_is_date_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_date_available',
        ),
    ]
